# Import

In [1]:
import numpy as np
import pandas as pd

from pyMSOO.MFEA.model import SM_MFEA
from pyMSOO.utils.Crossover import *
from pyMSOO.utils.Mutation import *
from pyMSOO.utils.Selection import *
from pyMSOO.utils.DimensionAwareStrategy import DaS_strategy

from pyMSOO.utils.EA import * 
from pyMSOO.MFEA.benchmark.continous.CEC17 import CEC17_benchmark 
from pyMSOO.MFEA.benchmark.continous.WCCI22 import WCCI22_benchmark

from pyMSOO.utils.MultiRun.RunMultiTime import * 
from pyMSOO.utils.MultiRun.RunMultiBenchmark import * 

# Run

In [2]:
# tasks, IndClass = CEC17_benchmark.get_2tasks_benchmark(1)
# tasks, IndClass = WCCI22_benchmark.get_complex_benchmark(1)
tasks, IndClass = CEC17_benchmark.get_10tasks_benchmark()

1 time

In [3]:
SM_SBX = SM_MFEA.model()
SM_SBX.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
)
solve1 = SM_SBX.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 02m 10.13s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 1.98E-26  3.47E-26  0.00E+00  0.00E+00  2.10E-24  4.31E-14  0.00E+00  3.40E+03  0.00E+00  3.08E+01  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99758, 99928, 99828, 100188, 100108, 100518, 100536, 99970, 99206, 99990]
END!


In [8]:
solve1[1]

Genes: [0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9
 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9
 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
Skill_factor: 1

In [11]:
decode_solve=[]
for i in range(len(tasks)):
    decode_solve.append((tasks[i].encode(tasks[i].get_global(solve1[i])), tasks[i](solve1[i])))
    

In [12]:
decode_solve[1]


(array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 3.473512337869159e-26)

In [4]:
SM_DaS = SM_MFEA.model()
SM_DaS.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
    dimension_strategy= DaS_strategy(eta= 3)
)
solve2 = SM_DaS.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 02m 26.96s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 2.10E-26  1.86E-26  0.00E+00  0.00E+00  6.86E-23  4.31E-14  0.00E+00  1.18E+02  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99838, 100258, 100214, 100418, 99598, 100142, 99806, 99114, 100240, 100402]
END!
